[package]
name = "simult"
version = "0.2.0"
edition = "2021"

[dependencies]
futures = "0.3"
reqwest = { version = "0.11", features = ["stream"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
url = "2.5"